version: '1.0'
source_cfg: C:\Users\mibnouba\OneDrive - Capgemini\Documents\Client\MDOOR_DEV_SPx_Baie2_v21\MDOOR_DEV_SPx_Baie2_v21\Stellantis_1605_MDOOR_V2_CANoev11.cfg
signals: []
aliases: {}
missing_signals: []
